services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - uploads_data:/app/uploads
    env_file:
      - .env  # Carrega todas as variáveis do arquivo .env  
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      # A URL agora é construída com as variáveis do .env
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # O serviço do banco de dados também usa as variáveis para a inicialização
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env  # Carrega as variáveis do banco (POSTGRES_USER, etc.)  

  backup:
    image: postgres:16
    volumes:
      - ./scripts:/scripts
      - ./backups:/backups
    env_file:
      - .env
    environment:
      - PGHOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    command: ["/scripts/backup.sh"]

    # --- NOVO SERVIÇO ADICIONADO AQUI ---
  restore:
    image: postgres:16
    volumes:
      # Mapeia a pasta de backups para que o pg_restore possa lê-la
      - ./backups:/backups
    env_file:
      - .env
    environment:
      - PGHOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    # O entrypoint é o comando que será executado.
    # Ele espera receber o nome do arquivo como argumento.
    entrypoint: ["pg_restore", "-U", "admin", "-d", "mdrh_db", "--clean", "--if-exists"]

volumes:
  postgres_data:
  uploads_data:
  backups_data: # Declara o novo volume para os backups    