"""Adiciona status aos avisos

Revision ID: 06340524eede
Revises: 34bcdf8e24ae
Create Date: 2025-08-05 12:17:40.918303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06340524eede'
down_revision = '34bcdf8e24ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aviso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='Ativo'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aviso', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
