"""Adiciona protocolo a denuncias

Revision ID: 06ff885842fe
Revises: b70581662283
Create Date: 2025-08-27 19:08:54.502302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ff885842fe'
down_revision = 'b70581662283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocolo', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_denuncia_protocolo'), ['protocolo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_denuncia_protocolo'))
        batch_op.drop_column('protocolo')

    # ### end Alembic commands ###
