"""Adiciona anexos ao canal de denuncias

Revision ID: 117d0884ff01
Revises: 2440e8a44dd2
Create Date: 2025-08-27 14:59:17.165591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117d0884ff01'
down_revision = '2440e8a44dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('denuncia_anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo_original', sa.String(length=255), nullable=False),
    sa.Column('path_armazenamento', sa.String(length=512), nullable=False),
    sa.Column('denuncia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['denuncia_id'], ['denuncia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_armazenamento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('denuncia_anexo')
    # ### end Alembic commands ###
