"""Melhorando tabela de Documentos

Revision ID: 1ee9d493b860
Revises: 246fb2b99f38
Create Date: 2025-09-09 13:48:07.172191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ee9d493b860'
down_revision = '246fb2b99f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('obrigatorio_na_admissao', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('requisicao_documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_ultima_atualizacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('observacoes_rh', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tipo_documento_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('documento_enviado_id', sa.Integer(), nullable=True))
        batch_op.alter_column('data_requisicao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('solicitante_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_requisicao_documento_destinatario_id'), ['destinatario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requisicao_documento_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'documento', ['documento_enviado_id'], ['id'])
        batch_op.create_foreign_key(None, 'tipo_documento', ['tipo_documento_id'], ['id'])
        batch_op.drop_column('tipo_documento')
        batch_op.drop_column('observacao')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_login_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('primeiro_login_completo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('primeiro_login_completo')
        batch_op.drop_column('ultimo_login_em')

    with op.batch_alter_table('requisicao_documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_documento', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_requisicao_documento_status'))
        batch_op.drop_index(batch_op.f('ix_requisicao_documento_destinatario_id'))
        batch_op.alter_column('solicitante_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('data_requisicao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('documento_enviado_id')
        batch_op.drop_column('tipo_documento_id')
        batch_op.drop_column('observacoes_rh')
        batch_op.drop_column('data_ultima_atualizacao')

    op.drop_table('tipo_documento')
    # ### end Alembic commands ###
