"""Adiciona username a tabela usuario

Revision ID: 246fb2b99f38
Revises: 47633cf53555
Create Date: 2025-09-05 15:05:02.376910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246fb2b99f38'
down_revision = '47633cf53555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuario_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
