"""Adiciona campos de revisao a tabela de documentos

Revision ID: 27f19675bd8e
Revises: 296e426c6b15
Create Date: 2025-08-05 14:58:22.123456

"""
from alembic import op # type: ignore
import sqlalchemy as sa # type: ignore


# revision identifiers, used by Alembic.
revision = '27f19675bd8e'
down_revision = '296e426c6b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        # Adiciona as colunas, com 'status' sendo nula temporariamente
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('revisor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_revisao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('observacao_revisao', sa.Text(), nullable=True))
        
        # --- CORREÇÃO APLICADA ---
        # Cria a chave estrangeira com um nome explícito
        batch_op.create_foreign_key(
            batch_op.f('fk_documento_revisor_id_usuario'), 
            'usuario', 
            ['revisor_id'], 
            ['id']
        )

    # --- CORREÇÃO ADICIONAL ---
    # Define um valor padrão para a coluna 'status' em todas as linhas existentes
    op.execute("UPDATE documento SET status = 'Pendente de Revisão'")

    # Agora, altera a coluna 'status' para não permitir valores nulos
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        # --- CORREÇÃO APLICADA ---
        # Remove a chave estrangeira usando o mesmo nome explícito
        batch_op.drop_constraint(batch_op.f('fk_documento_revisor_id_usuario'), type_='foreignkey')
        batch_op.drop_column('observacao_revisao')
        batch_op.drop_column('data_revisao')
        batch_op.drop_column('revisor_id')
        batch_op.drop_column('status')
    # ### end Alembic commands ###