"""Aprimora fluxo de revisao de documentos

Revision ID: 296e426c6b15
Revises: 06340524eede
Create Date: 2025-08-05 12:53:44.546576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296e426c6b15'
down_revision = '06340524eede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requisicao_id', sa.Integer(), nullable=True))
        # --- LINHA CORRIGIDA ---
        # Adicionamos um nome explícito para a Foreign Key, usando a convenção do Alembic.
        batch_op.create_foreign_key(batch_op.f('fk_documento_requisicao_id_requisicao_documento'), 'requisicao_documento', ['requisicao_id'], ['id'])

    with op.batch_alter_table('requisicao_documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisicao_documento', schema=None) as batch_op:
        batch_op.drop_column('observacao')

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('requisicao_id')

    # ### end Alembic commands ###
