"""Adiciona campo de arquivamento para avisos

Revision ID: 34bcdf8e24ae
Revises: 673cb8d17994
Create Date: 2025-07-31 17:59:56.312040

"""
from alembic import op # type: ignore
import sqlalchemy as sa # type: ignore


# revision identifiers, used by Alembic.
revision = '34bcdf8e24ae'
down_revision = '673cb8d17994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aviso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivado', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aviso', schema=None) as batch_op:
        batch_op.drop_column('arquivado')
    # ### end Alembic commands ###
