"""Schema inicial com correções

Revision ID: 36cae8e00e8a
Revises: 
Create Date: 2025-08-20 14:13:25.902070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36cae8e00e8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('setor', sa.String(length=100), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('contato_emergencia_nome', sa.String(length=120), nullable=True),
    sa.Column('contato_emergencia_telefone', sa.String(length=50), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('apelido', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('funcionario_sistemas',
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('sistema_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['sistema_id'], ['sistema.id'], ),
    sa.PrimaryKeyConstraint('funcionario_id', 'sistema_id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('senha_provisoria', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('funcionario_id')
    )
    op.create_table('aviso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_publicacao', sa.DateTime(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('arquivado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('avaliador_id', sa.Integer(), nullable=False),
    sa.Column('avaliado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avaliado_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['avaliador_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissoes_usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'permissao_id')
    )
    op.create_table('ponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_ajuste', sa.Date(), nullable=False),
    sa.Column('tipo_ajuste', sa.String(length=50), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('path_assinado', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.Column('observacao_rh', sa.Text(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('revisor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['revisor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisicao_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_requisicao', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destinatario_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aviso_anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo_original', sa.String(length=255), nullable=False),
    sa.Column('path_armazenamento', sa.String(length=512), nullable=False),
    sa.Column('aviso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aviso_id'], ['aviso.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_armazenamento')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('path_armazenamento', sa.String(length=512), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.Column('requisicao_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('revisor_id', sa.Integer(), nullable=True),
    sa.Column('data_revisao', sa.DateTime(), nullable=True),
    sa.Column('observacao_revisao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['requisicao_id'], ['requisicao_documento.id'], ),
    sa.ForeignKeyConstraint(['revisor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_armazenamento')
    )
    op.create_table('log_ciencia_aviso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aviso_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_ciencia', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aviso_id'], ['aviso.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_ciencia_aviso')
    op.drop_table('documento')
    op.drop_table('aviso_anexo')
    op.drop_table('requisicao_documento')
    op.drop_table('ponto')
    op.drop_table('permissoes_usuarios')
    op.drop_table('feedback')
    op.drop_table('aviso')
    op.drop_table('usuario')
    op.drop_table('funcionario_sistemas')
    op.drop_table('sistema')
    op.drop_table('permissao')
    op.drop_table('funcionario')
    # ### end Alembic commands ###
