"""Adiciona campo de feedback do RH as denuncias

Revision ID: 3caef1cc31fa
Revises: 06ff885842fe
Create Date: 2025-08-27 19:22:21.111250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3caef1cc31fa'
down_revision = '06ff885842fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_rh', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncia', schema=None) as batch_op:
        batch_op.drop_column('feedback_rh')

    # ### end Alembic commands ###
