"""Add Setor ao Ativo

Revision ID: 3d5abd8b288a
Revises: cd700a1e7d67
Create Date: 2025-11-21 15:02:45.213709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5abd8b288a'
down_revision = 'cd700a1e7d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ativo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'setor', ['setor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ativo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('setor_id')

    # ### end Alembic commands ###
