"""Add Protocolo ChamadoTI

Revision ID: 4372fcedc67a
Revises: 66ec6e4c0733
Create Date: 2025-11-21 14:10:12.834446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4372fcedc67a'
down_revision = '66ec6e4c0733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamado_ti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocolo', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_chamado_ti_protocolo'), ['protocolo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamado_ti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chamado_ti_protocolo'))
        batch_op.drop_column('protocolo')

    # ### end Alembic commands ###
