"""Adiciona campoo de tema ao usuario

Revision ID: 47633cf53555
Revises: 73a715a570d8
Create Date: 2025-09-04 15:58:10.867251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47633cf53555'
down_revision = '73a715a570d8'
branch_labels = None
depends_on = None


# Dentro do novo arquivo de migração
def upgrade():
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=50), nullable=False, server_default='light'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
