"""Adiciona funcionalidades de documentos

Revision ID: 477693e05880
Revises: 484e7bcf9019
Create Date: 2025-12-02 19:26:16.863742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477693e05880'
down_revision = '484e7bcf9019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorrente', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_base', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('intervalo_dias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ativa', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.drop_column('ativa')
        batch_op.drop_column('intervalo_dias')
        batch_op.drop_column('data_base')
        batch_op.drop_column('recorrente')

    # ### end Alembic commands ###
