"""Adiciona workflow de solicitacao e aprovacao

Revision ID: 484e7bcf9019
Revises: 70245a0e4989
Create Date: 2025-12-01 14:29:30.184805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484e7bcf9019'
down_revision = '70245a0e4989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('status_geral', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_aprovacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('aprovador_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_acao', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aprovador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao_aprovador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('aprovador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aprovador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requisicao_documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitacao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'solicitacao', ['solicitacao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisicao_documento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('solicitacao_id')

    op.drop_table('solicitacao_aprovador')
    op.drop_table('documento_aprovacao')
    op.drop_table('solicitacao')
    # ### end Alembic commands ###
