"""Adiciona campo ultimo_logon_ad

Revision ID: 4bd3a4cd983e
Revises: 3d5abd8b288a
Create Date: 2025-11-25 14:44:19.179105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd3a4cd983e'
down_revision = '3d5abd8b288a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_logon_ad', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('ultimo_logon_ad')

    # ### end Alembic commands ###
