"""Adiciona tabela de anexos para avisos

Revision ID: 673cb8d17994
Revises: ff5997eec2aa
Create Date: 2025-07-31 17:13:13.721226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673cb8d17994'
down_revision = 'ff5997eec2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aviso_anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo_original', sa.String(length=255), nullable=False),
    sa.Column('path_armazenamento', sa.String(length=512), nullable=False),
    sa.Column('aviso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aviso_id'], ['aviso.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_armazenamento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aviso_anexo')
    # ### end Alembic commands ###
