"""ajuste_ciclo_e_avisos

Revision ID: 70245a0e4989
Revises: fb3149e32bbb
Create Date: 2025-11-28 15:47:59.797337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70245a0e4989'
down_revision = 'fb3149e32bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aviso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_supervisores', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('target_diretoria', sa.Boolean(), nullable=False))
        batch_op.drop_column('apenas_lideranca')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aviso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apenas_lideranca', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('target_diretoria')
        batch_op.drop_column('target_supervisores')

    # ### end Alembic commands ###
