"""Merge Final

Revision ID: 884b0099ac0f
Revises: 
Create Date: 2025-11-25 18:30:35.144526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884b0099ac0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_ti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('localizacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_sala', sa.String(length=100), nullable=False),
    sa.Column('andar', sa.String(length=50), nullable=True),
    sa.Column('planta_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_sala')
    )
    op.create_table('ativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('tag_patrimonio', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('localizacao_id', sa.Integer(), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('descricao_ad', sa.String(length=255), nullable=True),
    sa.Column('sistema_operacional', sa.String(length=100), nullable=True),
    sa.Column('ultimo_logon_ad', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['localizacao_id'], ['localizacao.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ativo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ativo_hostname'), ['hostname'], unique=True)
        batch_op.create_index(batch_op.f('ix_ativo_numero_serie'), ['numero_serie'], unique=True)
        batch_op.create_index(batch_op.f('ix_ativo_tag_patrimonio'), ['tag_patrimonio'], unique=True)

    op.create_table('chamado_ti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(length=20), nullable=True),
    sa.Column('arquivado', sa.Boolean(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('prioridade', sa.String(length=50), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('data_limite_sla', sa.DateTime(), nullable=True),
    sa.Column('categoria_ti_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_atribuido_id', sa.Integer(), nullable=True),
    sa.Column('ativo_associado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ativo_associado_id'], ['ativo.id'], ),
    sa.ForeignKeyConstraint(['categoria_ti_id'], ['categoria_ti.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['tecnico_atribuido_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chamado_ti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chamado_ti_protocolo'), ['protocolo'], unique=True)

    op.create_table('emprestimo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_responsavel_id', sa.Integer(), nullable=False),
    sa.Column('data_emprestimo', sa.DateTime(), nullable=True),
    sa.Column('data_prevista_devolucao', sa.Date(), nullable=True),
    sa.Column('data_devolucao_real', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['tecnico_responsavel_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chamado_anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo_original', sa.String(length=255), nullable=False),
    sa.Column('path_armazenamento', sa.String(length=512), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamado_ti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_armazenamento')
    )
    op.create_table('chamado_comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('data_comentario', sa.DateTime(), nullable=True),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamado_ti.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chamado_comentario')
    op.drop_table('chamado_anexo')
    op.drop_table('emprestimo')
    with op.batch_alter_table('chamado_ti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chamado_ti_protocolo'))

    op.drop_table('chamado_ti')
    with op.batch_alter_table('ativo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ativo_tag_patrimonio'))
        batch_op.drop_index(batch_op.f('ix_ativo_numero_serie'))
        batch_op.drop_index(batch_op.f('ix_ativo_hostname'))

    op.drop_table('ativo')
    op.drop_table('localizacao')
    op.drop_table('categoria_ti')
    # ### end Alembic commands ###
