"""Adiciona categoria as denuncias

Revision ID: b70581662283
Revises: 117d0884ff01
Create Date: 2025-08-27 15:13:24.783621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70581662283'
down_revision = '117d0884ff01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncia', schema=None) as batch_op:
        # Adicionamos server_default para preencher as linhas existentes.
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=False, server_default='Outros'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncia', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
