"""Adiciona data_desligamento ao funcionario

Revision ID: bb5b1cc18a47
Revises: c4d7a479a3c6
Create Date: 2025-08-21 12:45:35.972914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5b1cc18a47'
down_revision = 'c4d7a479a3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_desligamento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionario', schema=None) as batch_op:
        batch_op.drop_column('data_desligamento')

    # ### end Alembic commands ###
