"""Adiciona modelos de usuario, permissoes e funcionalidades de RH

Revision ID: c02e10825ea5
Revises: 8cc7a9d4a542
Create Date: 2025-07-31 10:20:30.766592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02e10825ea5'
down_revision = '8cc7a9d4a542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('path_armazenamento', sa.String(length=512), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_armazenamento')
    )
    op.create_table('funcionario_sistemas',
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('sistema_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['sistema_id'], ['sistema.id'], ),
    sa.PrimaryKeyConstraint('funcionario_id', 'sistema_id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('funcionario_id')
    )
    op.create_table('aviso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_publicacao', sa.DateTime(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('avaliador_id', sa.Integer(), nullable=False),
    sa.Column('avaliado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avaliado_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['avaliador_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissoes_usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'permissao_id')
    )
    op.create_table('log_ciencia_aviso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aviso_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_ciencia', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aviso_id'], ['aviso.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('funcionario', schema=None) as batch_op:
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('cargo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('setor',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('contato_emergencia_nome',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('contato_emergencia_telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('beneficios_ativos')

    with op.batch_alter_table('sistema', schema=None) as batch_op:
       batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=True))
       # Adicionamos um nome para a constraint de unicidade
       batch_op.create_unique_constraint("uq_sistema_nome", ['nome'])
       batch_op.drop_column('status')
       batch_op.drop_column('funcionario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sistema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funcionario_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=10), nullable=False))
        batch_op.create_foreign_key(None, 'funcionario', ['funcionario_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('categoria')

    with op.batch_alter_table('funcionario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beneficios_ativos', sa.BOOLEAN(), nullable=False))
        batch_op.alter_column('contato_emergencia_telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('contato_emergencia_nome',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('setor',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('cargo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    op.drop_table('log_ciencia_aviso')
    op.drop_table('permissoes_usuarios')
    op.drop_table('feedback')
    op.drop_table('aviso')
    op.drop_table('usuario')
    op.drop_table('funcionario_sistemas')
    op.drop_table('documento')
    op.drop_table('permissao')
    # ### end Alembic commands ###
