"""Adiciona campo de consentimento ao usuario

Revision ID: c4d7a479a3c6
Revises: 36cae8e00e8a
Create Date: 2025-08-20 20:05:27.779234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d7a479a3c6'
down_revision = '36cae8e00e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_consentimento', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('data_consentimento')

    # ### end Alembic commands ###
