"""Add Campo Arquivado Helpdesk

Revision ID: cd700a1e7d67
Revises: 4372fcedc67a
Create Date: 2025-11-21 14:38:05.534383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd700a1e7d67'
down_revision = '4372fcedc67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamado_ti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivado', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamado_ti', schema=None) as batch_op:
        batch_op.drop_column('arquivado')

    # ### end Alembic commands ###
