"""Adiciona tabela para sugestoes de vinculo com AD

Revision ID: ceb6a60f8c94
Revises: 5b2e3f8a1c9d
Create Date: 2025-10-03 11:16:38.312601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb6a60f8c94'
down_revision = '5b2e3f8a1c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vinculo_ad_sugestao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_nome', sa.String(length=120), nullable=False),
    sa.Column('ad_username', sa.String(length=120), nullable=False),
    sa.Column('ad_display_name', sa.String(length=120), nullable=False),
    sa.Column('pontuacao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requisicao_documento', schema=None) as batch_op:
        batch_op.alter_column('tipo_documento_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('primeiro_login_completo',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('primeiro_login_completo',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('requisicao_documento', schema=None) as batch_op:
        batch_op.alter_column('tipo_documento_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('vinculo_ad_sugestao')
    # ### end Alembic commands ###
