"""ajustes_avisos_setorizados

Revision ID: fb3149e32bbb
Revises: 4bd3a4cd983e
Create Date: 2025-11-28 15:25:35.512440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3149e32bbb'
down_revision = '4bd3a4cd983e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aviso_setores',
    sa.Column('aviso_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aviso_id'], ['aviso.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('aviso_id', 'setor_id')
    )
    with op.batch_alter_table('aviso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publico_geral', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('apenas_lideranca', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aviso', schema=None) as batch_op:
        batch_op.drop_column('apenas_lideranca')
        batch_op.drop_column('publico_geral')

    op.drop_table('aviso_setores')
    # ### end Alembic commands ###
