"""Adicionando tabela Artigo

Revision ID: fe638cd9c42a
Revises: ceb6a60f8c94
Create Date: 2025-10-29 14:44:18.933626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe638cd9c42a'
down_revision = 'ceb6a60f8c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artigos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_publicacao', sa.DateTime(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('link_externo', sa.String(length=500), nullable=True),
    sa.Column('path_anexo', sa.String(length=500), nullable=True),
    sa.Column('nome_anexo_original', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artigos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artigos_data_publicacao'), ['data_publicacao'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artigos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artigos_data_publicacao'))

    op.drop_table('artigos')
    # ### end Alembic commands ###
