"""Adiciona tabela de requisicao de documentos

Revision ID: ff5997eec2aa
Revises: a6923be64e1e
Create Date: 2025-07-31 15:59:31.519733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5997eec2aa'
down_revision = 'a6923be64e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisicao_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_requisicao', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destinatario_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisicao_documento')
    # ### end Alembic commands ###
